"""Add customer id in order class

Revision ID: a0450540dbd4
Revises: 584917a4caa2
Create Date: 2022-07-12 17:22:36.467210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0450540dbd4'
down_revision = '584917a4caa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('customerId', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'customerId')
    # ### end Alembic commands ###
